# Generated by Django 2.1.7 on 2019-04-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190416_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('created', 'Created')], default='created', max_length=120),
        ),
    ]
