# Generated by Django 2.1.7 on 2019-03-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0003_auto_20190302_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='abd', max_length=100),
        ),
    ]
