# Generated by Django 2.1.7 on 2019-03-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0002_join_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
