# Generated by Django 2.1.7 on 2019-04-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='type',
            field=models.CharField(choices=[('billing', 'billing'), ('shipping', 'shipping')], max_length=120),
        ),
    ]
